# Generated by Django 4.0 on 2021-12-15 16:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Your Name ')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name ')),
                ('position', models.CharField(blank=True, max_length=150, null=True, verbose_name='Position ')),
                ('date_hire', models.DateField(blank=True, default=datetime.datetime(2021, 12, 15, 22, 47, 11, 273707))),
                ('salary', models.IntegerField(default=0, verbose_name='Amount of wages ')),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.boss')),
            ],
        ),
    ]
