# Generated by Django 4.0 on 2021-12-15 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_hire',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 12, 15, 22, 47, 33, 245410)),
        ),
    ]
