# Generated by Django 4.0 on 2021-12-15 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_employee_date_hire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_hire',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 12, 15, 22, 50, 53, 971389)),
        ),
    ]
